name: Deploy and Restart odoo19-web-1 Container

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Ensure repo is initialized
        run: |
          echo "Pulling Changes...."
          REPO_URL=git@github.com:itsosamanadeem/optixodoo.git
          cd ~/odoo19/custom-addons
          git fetch origin
          git checkout staging
          git reset --hard origin/staging
          
      - name: Restart Docker container odoo19-web-1
        run: |
          echo "Restarting Docker container..."
          docker restart odoo19-web-1